menu:
  - name: Home
    url: /  
  - name: Background
    url: /cv
  - name: Publications
    url: /publications
  - name: CV
    url: /cv/Sichen_Jin_Resume.pdf
social:
  - icon: github
    link: 'https://github.com/chenehk'
  - icon: instagram
    link: 'https://www.instagram.com/chen_ehk/'
  - icon: linkedin
    link: 'https://www.linkedin.com/in/sichen-jin-993745218/'
